export interface Partenaire {
  nom: string;
  logo?: string;
}

// Liste non exhaustive — donne un aperçu des maisons partenaires.
export const partenaires: Partenaire[] = [
  { nom: "Edouard Denis" },
  { nom: "CityA Immobilier" },
  { nom: "Imodéus" },
  { nom: "Cogedim" },
  { nom: "Tagerim" },
  { nom: "LP Promotion" },
  { nom: "Pierre & Passion" },
  { nom: "Vinci Immobilier" },
  { nom: "Perl" },
  { nom: "Senioriales" },
  { nom: "Urbis Réalisations" },
  { nom: "Elyade" },
  { nom: "Foncia Immo Neuf" },
  { nom: "Sporting Promotion" },
  { nom: "Saint-Agne Immobilier" },
  { nom: "ODDO BHF" },
  { nom: "Advenis" },
  { nom: "Sofidy" },
  { nom: "Norma Capital" },
  { nom: "Vie Plus" },
  { nom: "NextStage" },
  { nom: "Odyssée Venture" },
  { nom: "Inter Invest" },
  { nom: "Eiffel Investment Group" },
  { nom: "La Française" },
  { nom: "Alderan" },
  { nom: "Novaxia" },
  { nom: "Atland Voisin" },
  { nom: "Groupe Apicil" },
  { nom: "Eres" },
  { nom: "CFCAL" },
  { nom: "Crédit Agricole" },
  { nom: "Société Générale" },
  { nom: "Arkéa Banque Privée" },
  { nom: "MyMoneyBank" },
  { nom: "LCL" },
  { nom: "Banque Populaire" },
  { nom: "Groupe Caisse d'Épargne" },
  { nom: "BNP Paribas" },
  { nom: "Activimmo" },
  { nom: "Alta Convictions" },
  { nom: "Atream Hôtels" },
  { nom: "Comète" },
  { nom: "Corum Eurion" },
  { nom: "Corum Origin" },
  { nom: "Epargne Pierre" },
  { nom: "Epargne Pierre Europe" },
  { nom: "Eurovalys" },
  { nom: "Immorente" },
  { nom: "LF Avenir Santé" },
  { nom: "NCAP Régions" },
  { nom: "Osmo Energie" },
  { nom: "Périal Opportunités" },
  { nom: "Sofidy Europe Invest" },
  { nom: "Transitions Europe" },
];
